language: ruby
rvm:
- 2.7.1
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE retrobot_test;'
install:
- nvm install
- nvm use
- wget -N http://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
- gem install bundler -v 1.17.3
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
script:
- RAILS_ENV=test bin/rails db:migrate --trace
- bin/rails test
- yarn install --pure-lockfile
- yarn run test:ci
- NODE_ENV=test npx percy exec -- bin/rails test:system
after_success:
- bundle exec codeclimate-test-reporter
dist: trusty
cache:
  bundler: true
  directories:
  - node_modules
addons:
  code_climate:
    secure: hrN+2VIfMh1Iu3yeiqYU0Oj65sZWiWnM4Tb6eLJIBE28uqwu0J4tGy68x9SxeiTzo2OnhVG7c91eRfjX6xJwMfipOt8qIB4Z84xS5+pPDfK74QaLx0c/s+SznxIWRhLRg6qudfYvNXm7Ru+tHhEMW+39yIPCEGOwlS44+sXVuWl7zHoDia6RZa4fLTEhS8E2wIRIDP7Dzup7Fd7GLjCftQu7YdcxMSooIslrGH4xkRAET4lFAGv3/lABoFmyz7djWPR/wUO9fqoHunzp5z3nqPfr2lDzvh3ok8717ld7kUj9yzR7UgRUOV76QG21wXFlXRoH6Fh0/Dfrua8Wn4TbWPNUaVNG6OYy5YzOpKq5vrcPWjl2frP9HxmHBIkCCKhWkmdZoaUux5UjiyGyhv1cHp3waydyDBjzxch9EZoczt1XikmlL3p1zsG483pFrojiyvlzeiBRlGnj1ZrIaVtCzYEEW4gatT/LOIrDf7y4FN5fwnfAOlRbZYeEEOgXh1lJl9JxJYq0gNkZ46wZK7jRALzko94qoR+GsrNfJiQy2gJG+EB0J7Ak3MejzveTxLoOH+AnRKVsrVAO8hJhSYd94deztIeUX2xUAxC+nrdJV3caTMGUzORTD7HwJJT0HyFB57ee/Tb0CI7IsgA7M9/m68sXwakd/dLIV5nr+E0TbwE=
  chrome: stable
